### ISSUE TITLE
Add random verse from given song endpoint

### ISSUE THREAD

**Issue by Kornelos** [Kornelos/Peja#2]

**Comment by Nikniknikm** [comment]
I'd like to work on this

**Comment by julzerinos** [comment]
I am senior jhava champion. I can do this, but you must pay me 420$. I will do 400000000000000000 commits, each will contain only one letter. Once you collect all the commits, the letters will spell out a treasure map. You fill search long and hard - but once you reach the tresure youe will notice that it was the journey that was imnportant all almong. Also there is no tresure it is 4$ coupon for heroku.

**Comment by Kornelos** [comment]
this is a javascript sir

**Comment by julzerinos** [comment]
Understandable have a nice day

**Comment by Kornelos** [comment]
blessing to you dear sir

**Comment by julzerinos** [comment]
yes
